### ISSUE TITLE
Crash Issue 1.21.4

### ISSUE THREAD

**Issue by interactii** [Loxoz/ContainerSearcher#3]
I mod crashes when opening some chests in 1.21.4. The chests that seem to cause an issue contain items with custom enchantments that are not in vanilla servers (such as a fishing rod with Aqua Affinity and so on)

[CM Crash.txt](https://github.com/user-attachments/files/18815133/CM.Crash.txt)

Crash log is attached.

**Comment by Loxoz** [comment]
1.21.4 is technically not fully supported I believe, I updated this mod for 1.21.3 and then tried to launch and test basic features on 1.21.4, called it a day and then marked this mod as working on 1.21.4. But it seems that in some specific cases 1.21.4 is not fully supported.

This will presumably be fixed when I "officially" update to 1.21.4 or later. There also seems to be another issue with enchantment levels higher than vanilla, which I will try to keep in mind when updating.

**Comment by RainOfPain125** [comment]
I have the same issue, I installed this mod and crashed on the first chest I tried to open. I loaded the game again and checked other chests, and other chests were working.

```
[21:19:46] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'int net.minecraft.class_9280.comp_2382()'
	at knot/fr.loxoz.csearcher.core.CachedStack.a(CachedStack.java:61) ~[ContainerSearcher-0.3.1+mc1.21.3.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at knot/fr.loxoz.csearcher.core.CachedStack.a(CachedStack.java:43) ~[ContainerSearcher-0.3.1+mc1.21.3.jar:?]
	at knot/fr.loxoz.csearcher.core.CachedStack.of(CachedStack.java:61) ~[ContainerSearcher-0.3.1+mc1.21.3.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at knot/fr.loxoz.csearcher.core.CachedStack.ofList(CachedStack.java:96) ~[ContainerSearcher-0.3.1+mc1.21.3.jar:?]
	at knot/fr.loxoz.csearcher.CSearcher.updateCachedContainer(CSearcher.java:213) ~[ContainerSearcher-0.3.1+mc1.21.3.jar:?]
	at knot/fr.loxoz.csearcher.CSearcher.handleContainerScreenUpdate(CSearcher.java:179) ~[ContainerSearcher-0.3.1+mc1.21.3.jar:?]
	at knot/fr.loxoz.csearcher.core.CSMixinListener.onContainerUpdateSlots(CSMixinListener.java:41) ~[ContainerSearcher-0.3.1+mc1.21.3.jar:?]
	at knot/net.minecraft.class_1703.handler$zjm000$csearcher$a(class_1703.java:918) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1703.method_7610(class_1703.java:646) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_634.method_11153(class_634.java:1355) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2649.method_11439(class_2649.java:51) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2649.method_65081(class_2649.java:12) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1296) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:922) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:267) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```
It might be caused by servers with whatever plugin adds custom items/item appearances. Example shown.
![Image](https://github.com/user-attachments/assets/0f96143e-4469-4fb6-8331-d14722c81ecb)
"Chest Tracker" seems to work fine. But I prefer ContainerSearcher because it looks nicer. Hope the issue is resolved soon :]

**Comment by FireBird22** [comment]
Would you consider open sourcing the mod so people can contribute/update for the latest version?

**Comment by Loxoz** [comment]
I will do so in the near future, as discussed in this issue: #2. However, I barely have time to do anything right now. I will have more time from 14 July.

**Comment by Loxoz** [comment]
I have uploaded a [beta version](https://modrinth.com/mod/csearcher/version/0.3.2+beta1+mc1.21.4) for the 1.21.4. It fixes the issue with 1.21.4, but does so by no longer supporting custom model data.
Waiting for potential feedback before closing.
